
package com.kaisn.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://impl.service.kaisn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.AddEmployeeResponse")
    public boolean addEmployee(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.kaisn.ws.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.GetEmployeeResponse")
    public Employee getEmployee(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.kaisn.ws.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeList", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.GetEmployeeList")
    @ResponseWrapper(localName = "getEmployeeListResponse", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.GetEmployeeListResponse")
    public List<Employee> getEmployeeList(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updEmployee", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.UpdEmployee")
    @ResponseWrapper(localName = "updEmployeeResponse", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.UpdEmployeeResponse")
    public boolean updEmployee(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeListCount", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.GetEmployeeListCount")
    @ResponseWrapper(localName = "getEmployeeListCountResponse", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.GetEmployeeListCountResponse")
    public int getEmployeeListCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delEmployee", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.DelEmployee")
    @ResponseWrapper(localName = "delEmployeeResponse", targetNamespace = "http://impl.service.kaisn.com/", className = "com.kaisn.ws.DelEmployeeResponse")
    public boolean delEmployee(
            @WebParam(name = "arg0", targetNamespace = "")
                    Employee arg0);

}
